### ISSUE TITLE
Actividad 3 corregida: Fallo (ver descripción)

### ISSUE THREAD

**Issue by cborcar637** [ibonper0708/Unidad-3#3]
La función se llama `hola()` y debe llamarse `pedirDatos()` tal y como se indica en el PDF.

Cuando lo soluciones, no cierres la petición, simplemente responde a este mensaje para saber que lo has arreglado. Ya te pediré que lo cierres cuando lo revise.

**Comment by ibonper0708** [comment]
Ya lo he arreglado.

**Comment by cborcar637** [comment]
Hola. Lo has corregido en el archivo `script.js`, pero en el archivo `index.html` sigue igual. Ahora no funciona el botón porque hace una llamada a una función que no existe

**Comment by ibonper0708** [comment]
Hola. ¿Lo he corregido bien?

**Comment by cborcar637** [comment]
Sí. Cierro la solicitud
